"""
make_llm_judge_graphs.py

Creates graphs from the LLM judge evaluation outputs generated by llm_judge_eval.py.

Expected input files:
  llm_judge_results/model_summary.csv
  llm_judge_results/judgments_detailed.csv

Outputs:
  llm_judge_results/graphs/01_model_mean_scores_grouped_bar.png
  llm_judge_results/graphs/02_overall_resonance_bar_with_std.png
  llm_judge_results/graphs/03_semantic_vs_emotional_scatter.png
  llm_judge_results/graphs/04_score_distribution_boxplot_semantic_fit.png
  llm_judge_results/graphs/04_score_distribution_boxplot_emotional_fit.png
  llm_judge_results/graphs/04_score_distribution_boxplot_overall_resonance.png
  llm_judge_results/graphs/05_model_rank_by_metric.png
  llm_judge_results/graphs/README_graphs.txt

Run from repo root:
  python make_llm_judge_graphs.py
"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


BASE_DIR = Path(__file__).resolve().parent
RESULTS_DIR = BASE_DIR / "llm_judge_results"
SUMMARY_CSV = RESULTS_DIR / "model_summary.csv"
DETAILED_CSV = RESULTS_DIR / "judgments_detailed.csv"
GRAPH_DIR = RESULTS_DIR / "graphs"

MODEL_LABELS = {
    "rerank_retrieve": "Rerank",
    "track_1_clip_semantic": "Track 1\nCLIP",
    "track_2_blip_caption": "Track 2\nBLIP",
    "track_3_clip_sbert_mood": "Track 3\nMood",
    "track_4_handcrafted_cv": "Track 4\nHandcrafted",
}

METRIC_LABELS = {
    "semantic_fit": "Semantic Fit",
    "emotional_fit": "Emotional Fit",
    "overall_resonance": "Overall Resonance",
}


def load_data():
    if not SUMMARY_CSV.exists():
        raise FileNotFoundError(f"Missing summary file: {SUMMARY_CSV}")
    if not DETAILED_CSV.exists():
        raise FileNotFoundError(f"Missing detailed file: {DETAILED_CSV}")

    summary = pd.read_csv(SUMMARY_CSV)
    detailed = pd.read_csv(DETAILED_CSV)

    detailed = detailed.dropna(subset=["semantic_fit", "emotional_fit", "overall_resonance"])

    summary["model_label"] = summary["model_name"].map(MODEL_LABELS).fillna(summary["model_name"])
    detailed["model_label"] = detailed["model_name"].map(MODEL_LABELS).fillna(detailed["model_name"])

    order = summary.sort_values("overall_resonance_mean", ascending=False)["model_name"].tolist()
    labels_order = [MODEL_LABELS.get(m, m) for m in order]

    return summary, detailed, order, labels_order


def save_current_fig(filename):
    GRAPH_DIR.mkdir(parents=True, exist_ok=True)
    path = GRAPH_DIR / filename
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Saved {path}")


def plot_grouped_mean_scores(summary, order, labels_order):
    df = summary.set_index("model_name").loc[order]

    x = range(len(df))
    width = 0.25

    plt.figure(figsize=(11, 6))
    plt.bar([i - width for i in x], df["semantic_fit_mean"], width, label="Semantic Fit")
    plt.bar(list(x), df["emotional_fit_mean"], width, label="Emotional Fit")
    plt.bar([i + width for i in x], df["overall_resonance_mean"], width, label="Overall Resonance")

    plt.xticks(list(x), labels_order)
    plt.ylim(0, 5)
    plt.ylabel("Mean LLM Judge Score (1-5)")
    plt.title("Average LLM Judge Scores by Retrieval Model")
    plt.legend()
    plt.grid(axis="y", alpha=0.3)

    save_current_fig("01_model_mean_scores_grouped_bar.png")


def plot_overall_with_std(summary, order, labels_order):
    df = summary.set_index("model_name").loc[order]

    plt.figure(figsize=(10, 6))
    plt.bar(labels_order, df["overall_resonance_mean"], yerr=df["overall_resonance_std"], capsize=6)
    plt.ylim(0, 5)
    plt.ylabel("Overall Resonance Mean Score (1-5)")
    plt.title("Overall Resonance by Model with Standard Deviation")
    plt.grid(axis="y", alpha=0.3)

    save_current_fig("02_overall_resonance_bar_with_std.png")


def plot_semantic_vs_emotional(summary):
    plt.figure(figsize=(8, 6))

    for _, row in summary.iterrows():
        label = MODEL_LABELS.get(row["model_name"], row["model_name"])
        plt.scatter(row["semantic_fit_mean"], row["emotional_fit_mean"], s=120)
        plt.text(
            row["semantic_fit_mean"] + 0.03,
            row["emotional_fit_mean"] + 0.03,
            label.replace("\n", " "),
            fontsize=9,
        )

    plt.xlim(1, 5)
    plt.ylim(1, 5)
    plt.xlabel("Mean Semantic Fit")
    plt.ylabel("Mean Emotional Fit")
    plt.title("Semantic Fit vs. Emotional Fit by Model")
    plt.grid(alpha=0.3)

    save_current_fig("03_semantic_vs_emotional_scatter.png")


def plot_score_distribution_boxplots(detailed, order, labels_order):
    metrics = ["semantic_fit", "emotional_fit", "overall_resonance"]

    for metric in metrics:
        data = [
            detailed[detailed["model_name"] == model][metric].dropna().values
            for model in order
        ]

        plt.figure(figsize=(10, 6))
        plt.boxplot(data, labels=labels_order, showmeans=True)
        plt.ylim(0.5, 5.5)
        plt.ylabel("LLM Judge Score (1-5)")
        plt.title(f"Distribution of {METRIC_LABELS[metric]} Scores by Model")
        plt.grid(axis="y", alpha=0.3)

        filename = f"04_score_distribution_boxplot_{metric}.png"
        save_current_fig(filename)


def plot_model_rank_by_metric(summary, order, labels_order):
    rank_df = summary.copy()

    rank_df["semantic_rank"] = rank_df["semantic_fit_mean"].rank(ascending=False, method="min")
    rank_df["emotional_rank"] = rank_df["emotional_fit_mean"].rank(ascending=False, method="min")
    rank_df["overall_rank"] = rank_df["overall_resonance_mean"].rank(ascending=False, method="min")

    rank_df = rank_df.set_index("model_name").loc[order]

    x = range(len(rank_df))
    width = 0.25

    plt.figure(figsize=(11, 6))
    plt.bar([i - width for i in x], rank_df["semantic_rank"], width, label="Semantic Fit Rank")
    plt.bar(list(x), rank_df["emotional_rank"], width, label="Emotional Fit Rank")
    plt.bar([i + width for i in x], rank_df["overall_rank"], width, label="Overall Resonance Rank")

    plt.xticks(list(x), labels_order)
    plt.gca().invert_yaxis()
    plt.ylabel("Rank, Lower Is Better")
    plt.title("Model Rank by Evaluation Dimension")
    plt.legend()
    plt.grid(axis="y", alpha=0.3)

    save_current_fig("05_model_rank_by_metric.png")


def write_readme(summary):
    GRAPH_DIR.mkdir(parents=True, exist_ok=True)
    readme_path = GRAPH_DIR / "README_graphs.txt"
    best = summary.sort_values("overall_resonance_mean", ascending=False).iloc[0]

    text = f"""LLM Judge Graphs

Input files:
- {SUMMARY_CSV}
- {DETAILED_CSV}

Generated charts:
1. 01_model_mean_scores_grouped_bar.png
   Compares each model's mean semantic fit, emotional fit, and overall resonance.

2. 02_overall_resonance_bar_with_std.png
   Shows overall resonance mean with standard deviation error bars.

3. 03_semantic_vs_emotional_scatter.png
   Places each model by semantic fit and emotional fit.

4. 04_score_distribution_boxplot_semantic_fit.png
   Shows the distribution of semantic fit scores across images.

5. 04_score_distribution_boxplot_emotional_fit.png
   Shows the distribution of emotional fit scores across images.

6. 04_score_distribution_boxplot_overall_resonance.png
   Shows the distribution of overall resonance scores across images.

7. 05_model_rank_by_metric.png
   Shows each model's rank across the three evaluation dimensions.

Top model by overall resonance:
- {best["model_name"]}: {best["overall_resonance_mean"]:.3f}
"""
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"Saved {readme_path}")


def main():
    summary, detailed, order, labels_order = load_data()

    plot_grouped_mean_scores(summary, order, labels_order)
    plot_overall_with_std(summary, order, labels_order)
    plot_semantic_vs_emotional(summary)
    plot_score_distribution_boxplots(detailed, order, labels_order)
    plot_model_rank_by_metric(summary, order, labels_order)
    write_readme(summary)

    print()
    print(f"Done. Graphs are in: {GRAPH_DIR}")


if __name__ == "__main__":
    main()
